#!/bin/sh

cd /img
mkdir -p optimized
rm -rf optimized/* ## Remove all the old optimized images

if [[ -z "$QUALITY" ]]; then
  QUALITY=90
fi

if [[ -z "$DEBUG" ]]; then
  DBGA="-q"
  JDBGA=""
else
  DBGA="-v"
  JDBGA="-v"
fi

echo "processing png files"
find . -iname "*.png" | while IFS= read -r pathname; do
  echo $pathname;
  DIRPATH=$(dirname "$pathname")
  mkdir -p optimized/$DIRPATH
  pngcrush $DBGA -d optimized/$DIRPATH $pathname
done

echo "processing jpg files"
find . -iname "*.jpg" | while IFS= read -r pathname; do
  echo $pathname
  DIRPATH=$(dirname "$pathname")
  mkdir -p optimized/$DIRPATH
  cjpeg $JDBGA -outfile optimized/$pathname -quality $QUALITY $pathname
done

